import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 120,
    gap: 18,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
  },
  subtitle: {
    fontSize: 15,
    color: '#4a4f58',
    lineHeight: 22,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    shadowColor: '#101828',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 2,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1f2933',
  },
  scanButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#ff565f',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  savedContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  savedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  savedChipGhost: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ff565f',
  },
  savedText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0b1f3a',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionLink: {
    fontSize: 13,
    fontWeight: '600',
  },
  separator: {
    height: 1,
    backgroundColor: '#e3e7ef',
    marginVertical: 12,
  },
  trendingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  trendingIndex: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#ffe7ea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trendingIndexLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ff565f',
  },
  trendingContent: {
    flex: 1,
  },
  trendingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#0b1f3a',
  },
  trendingMeta: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
  filterRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#fff',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  filterLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0b1f3a',
  },
  categoryRow: {
    paddingVertical: 4,
    gap: 14,
  },
  categoryPill: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 18,
    gap: 14,
    minWidth: 220,
  },
  categoryName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  categoryCount: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4,
  },
  recentGrid: {
    gap: 12,
  },
  recentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 16,
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  recentTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0b1f3a',
  },
  recentMeta: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 2,
  },
});
