import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 120,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  welcomeLabel: {
    fontSize: 14,
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  headline: {
    fontSize: 28,
    fontWeight: '700',
    marginTop: 6,
  },
  notificationButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    position: 'relative',
  },
  notificationBadge: {
    minWidth: 18,
    paddingHorizontal: 5,
    height: 18,
    borderRadius: 9,
    position: 'absolute',
    top: -4,
    right: -4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationBadgeLabel: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '700',
  },
  searchCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    shadowColor: '#101828',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 3,
    marginBottom: 20,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#1f2933',
  },
  filterButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#ff565f',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyRow: {
    paddingVertical: 6,
    gap: 16,
  },
  storyItem: {
    alignItems: 'center',
    width: 72,
  },
  storyAvatarWrapper: {
    borderRadius: 34,
    padding: 3,
    backgroundColor: '#fff',
    shadowColor: '#0b1f3a',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 2,
  },
  storyLive: {
    borderWidth: 2,
    borderColor: '#ff565f',
  },
  storyAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  storyLabel: {
    marginTop: 8,
    fontSize: 12,
    color: '#4a4f58',
    fontWeight: '600',
  },
  sectionHeader: {
    marginTop: 24,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  actionLink: {
    fontSize: 14,
    fontWeight: '600',
  },
  searchResultsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  searchResultCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 12,
    gap: 12,
    shadowColor: '#101828',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 14,
    elevation: 2,
    width: '100%',
  },
  searchResultImage: {
    width: 70,
    height: 70,
    borderRadius: 12,
  },
  searchResultInfo: {
    flex: 1,
    gap: 4,
  },
  searchResultTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  searchResultPrice: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ff565f',
  },
  searchResultMeta: {
    fontSize: 12,
    color: '#6b7280',
  },
  emptyStateCard: {
    borderRadius: 16,
    padding: 16,
    gap: 6,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'flex-start',
  },
  emptyStateText: {
    fontSize: 15,
    fontWeight: '700',
  },
  emptyStateHint: {
    fontSize: 13,
    lineHeight: 18,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  categoryCard: {
    width: '30%',
    minWidth: 100,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    gap: 10,
  },
  categoryLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#0b1f3a',
    textAlign: 'center',
  },
  featuredRow: {
    gap: 16,
    paddingRight: 8,
  },
  featuredCard: {
    width: 260,
    borderRadius: 20,
    backgroundColor: '#fff',
    overflow: 'hidden',
    shadowColor: '#1f2933',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 24,
    elevation: 4,
  },
  featuredImageWrapper: {
    position: 'relative',
  },
  featuredImage: {
    width: '100%',
    height: 160,
  },
  badge: {
    position: 'absolute',
    top: 12,
    left: 12,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    shadowColor: '#0b1f3a',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ff565f',
    textTransform: 'uppercase',
  },
  boostedFlag: {
    position: 'absolute',
    right: 12,
    top: 12,
    backgroundColor: '#ff8a65',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  boostedText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  featuredInfo: {
    padding: 16,
    gap: 6,
  },
  featuredTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  featuredPrice: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ff565f',
  },
  featuredMeta: {
    fontSize: 13,
    color: '#4a4f58',
  },
  tipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  tipCard: {
    width: '47%',
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    gap: 10,
    shadowColor: '#0b1f3a',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 20,
    elevation: 3,
  },
  tipIconWrapper: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#ffe7ea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tipTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  tipDescription: {
    fontSize: 13,
    color: '#4a4f58',
    lineHeight: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    gap: 14,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalUser: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modalAvatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  modalSubtitle: {
    fontSize: 13,
    color: '#6b7280',
  },
  modalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 8,
  },
  modalLabel: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '600',
    width: 86,
  },
  modalValueRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'flex-end',
  },
  modalValue: {
    fontSize: 15,
    textAlign: 'right',
  },
  modalListing: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f8fafc',
    borderRadius: 14,
  },
  modalListingImage: {
    width: 64,
    height: 64,
    borderRadius: 12,
  },
  modalListingTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  modalListingNote: {
    fontSize: 12,
    color: '#6b7280',
    marginTop: 4,
  },
  modalActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  secondaryButton: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  primaryButton: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  readPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#d1fae5',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  readPillLabel: {
    color: '#0f5132',
    fontSize: 12,
    fontWeight: '700',
  },
});
