import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 120,
    gap: 24,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  avatarContainer: {
    position: 'relative',
  },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 28,
  },
  editAvatar: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: '#ff565f',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#101828',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 4,
  },
  userInfo: {
    flex: 1,
    gap: 6,
  },
  userName: {
    fontSize: 22,
    fontWeight: '700',
  },
  userMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  userMeta: {
    fontSize: 13,
    color: '#4a4f58',
  },
  settingsButton: {
    width: 42,
    height: 42,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ffd6da',
    alignItems: 'center',
    justifyContent: 'center',
  },
  highlightRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  highlightCard: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    alignItems: 'center',
    gap: 6,
    shadowColor: '#101828',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 3,
  },
  highlightValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  highlightLabel: {
    fontSize: 12,
    color: '#6b7280',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  sectionLink: {
    fontSize: 13,
    fontWeight: '600',
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
  },
  actionCard: {
    width: '47%',
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    gap: 12,
    shadowColor: '#101828',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 3,
  },
  actionIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#ffe7ea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  shopCard: {
    flexDirection: 'row',
    gap: 16,
    backgroundColor: '#101d34',
    borderRadius: 22,
    padding: 20,
    alignItems: 'center',
  },
  shopTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
  },
  shopSubtitle: {
    fontSize: 13,
    color: '#d1d5db',
    marginTop: 6,
    lineHeight: 18,
  },
  shopButton: {
    backgroundColor: '#ff565f',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 16,
  },
  shopButtonLabel: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },
  listingGrid: {
    gap: 16,
  },
  listingCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#101828',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 18,
    elevation: 3,
  },
  listingImage: {
    width: '100%',
    height: 160,
  },
  listingInfo: {
    padding: 16,
    gap: 6,
  },
  listingTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  listingPrice: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ff565f',
  },
  listingMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  listingMeta: {
    fontSize: 12,
    color: '#6b7280',
  },
  listingAction: {
    position: 'absolute',
    top: 16,
    right: 16,
    backgroundColor: 'rgba(255,255,255,0.92)',
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  feedbackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    shadowColor: '#101828',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 18,
    elevation: 3,
  },
  feedbackTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  feedbackSubtitle: {
    fontSize: 13,
    color: '#4a4f58',
    marginTop: 4,
    lineHeight: 18,
  },
  feedbackButton: {
    backgroundColor: '#ff565f',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 16,
  },
  feedbackButtonLabel: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },
});
