import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 120,
    gap: 18,
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
  },
  subtitle: {
    fontSize: 15,
    color: '#4a4f58',
    lineHeight: 22,
  },
  photoUpload: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderColor: '#f6d9dc',
    borderStyle: 'dashed',
  },
  photoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  photoHint: {
    fontSize: 13,
    color: '#6b7280',
    textAlign: 'center',
  },
  photoActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 4,
  },
  primaryButton: {
    backgroundColor: '#ff565f',
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
  },
  primaryButtonLabel: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },
  secondaryButton: {
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ff565f',
  },
  secondaryButtonLabel: {
    color: '#ff565f',
    fontWeight: '700',
    fontSize: 15,
  },
  inputGroup: {
    gap: 8,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#0b1f3a',
  },
  input: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    fontSize: 15,
    color: '#1f2933',
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  multiline: {
    minHeight: 120,
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    gap: 14,
  },
  half: {
    flex: 1,
  },
  selectInput: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 12,
    elevation: 2,
  },
  selectText: {
    fontSize: 15,
    color: '#0b1f3a',
    fontWeight: '600',
  },
  sectionHeader: {
    marginTop: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  stepList: {
    gap: 12,
  },
  stepCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    shadowColor: '#101828',
    shadowOpacity: 0.04,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    elevation: 2,
  },
  stepIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: '#ffe7ea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  stepDescription: {
    fontSize: 13,
    color: '#6b7280',
    marginTop: 4,
  },
  stepOrder: {
    width: 32,
    height: 32,
    borderRadius: 12,
    backgroundColor: '#0b1f3a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepOrderLabel: {
    color: '#fff',
    fontWeight: '700',
  },
  smartPricing: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    backgroundColor: '#f2f6ff',
    borderRadius: 20,
    padding: 20,
  },
  smartTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0b1f3a',
  },
  smartSubtitle: {
    fontSize: 13,
    color: '#4a4f58',
    marginTop: 4,
    lineHeight: 18,
  },
  switchButton: {
    paddingHorizontal: 8,
  },
  publishButton: {
    marginTop: 8,
  },
});
